services:
  postgres:
    image: postgres:16
    container_name: todo_pg
    environment:
      POSTGRES_USER: ${DB_USER:-todo_user}
      POSTGRES_PASSWORD: ${DB_PASS:-todo_pass}
      POSTGRES_DB: ${DB_NAME:-todo_db}
    ports:
      - "5432:5432"
    volumes:
      - todo_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  todo_pg_data:
